# Generated by Django 5.0.6 on 2024-05-27 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_cartorder_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderproducts',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='core.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
